# the BioSample accession
biosample_accession: SAMN27770976

# name of CSV file listing barcode runs to uploade
barcode_runs: barcode_runs_Duke-NUS_antibodies.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/tyler.n.starr_gmail.com_LMpRB4Tu

# Meaningful name for this sample's FTP folder:
ftp_subfolder: Duke-NUS_antibody_barcodes_v3
